### ISSUE TITLE
i cant import fibonacci in chapter 7

### ISSUE THREAD

**Issue by Luther1994** [PacktPublishing/Expert-Python-Programming_Second-Edition#2]
I've already installed the module successfully,but when i imported this module ,import error occured:no module named fibonacci.How can i solve this problem？
![2019-10-15 18-19-27屏幕截图](https://user-images.githubusercontent.com/34814143/66823292-8354d680-ef78-11e9-8ad0-aea49ee33156.png)

**Comment by zhangdavids** [comment]
老哥 没下文了吗

按照提示 你上面安装的时候 就应该没有成功吧

**Comment by zhangdavids** [comment]
```
from distutils.core import setup, Extension

fiboM = Extension("fibonacci", sources=["fibonacci.c"])

setup(
    name='MathExtension',
    version='1.0.0',
    description='This is a test',
    ext_modules=[fiboM])
```

我修改了setup.py 文件。 先 build 再install

**Comment by deepesh-packt** [comment]
Please reopen the issue if the issue still persists.
